import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Contact from '../Components/UI/Contact/Contact'
import Hero from '../Components/UI/Hero/Hero'
import SpecialtiesInfo from '../Components/UI/SpecialtiesInfo/SpecialtiesInfo'

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Katelyn Sansone - Marriage and Family Therapist</title>
        {/* Remember the seo meta tags also for browser and responsiveness */}
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <section className='mid-intro-blurb'>
        <aside className='blurb-with-img'>
          <div className='round-portrait'>
            <Image
              src='/img/closeUpShot.jpg'
              height={400}
              width={400}
              className='round-portrait__img'
              alt='Self-Portrait'
            />
          </div>
          <div className='blurb-body'>
            <h2>Katelyn Sansone</h2>
            <p className='small-blurb'>
              Hi, I&apos;m Katelyn. I&apos;m a Supervised Marriage and Family
              Therapist (S-MFT) in St. Louis, MO who works with individuals,
              couples, and families. I&apos;m trained to look at how others
              present in your life impact the distress one may be experiencing.
              Change, loss, and pain are inevitable pieces of the human
              experience. Often we need extra support to help navigate these
              difficult, overwhelming periods of time. Therapy can provide
              guidance and support in a warm, comforting space tailored for your
              specific struggles.
            </p>

            <div className='blurb-btn'>
              <Link href='/about'>
                <a>Learn more</a>
              </Link>
            </div>
          </div>
        </aside>
      </section>
      <section className='quote-parent'>
        <div className='color-overlay'>
          <div className='quote-container'>
            <h4>
              &quot;The quality of your life ultimately depends on the quality of
              your relationships . . . which are basically a reflection of your
              sense of decency, your ability to think of others, your generosity.
              &quot;
            </h4>
            <p>- Esther Perel</p>
          </div>
        </div>
      </section>
      <section className='info-block'>
        <aside className='info-block__sm-body'>
          <h3>Specialties</h3>
        </aside>
        <div className='info-block__widgets'>
          <SpecialtiesInfo />
          {/* <div className='info-block__icon'></div>
          <div className='info-block__icon'></div>
          <div className='info-block__icon'></div> */}
        </div>
      </section>
      <section className='contact-block'>
        <Contact />
      </section>
    </div>
  )
}
