import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Contact from '../Components/UI/Contact/Contact'
import Hero from '../Components/UI/Hero/Hero'
import SpecialtiesInfo from '../Components/UI/SpecialtiesInfo/SpecialtiesInfo'

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Kate Sansone's Website</title>
        {/* Remember the seo meta tags also for browser and responsiveness */}
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <section className='mid-intro-blurb'>
        <aside className='blurb-with-img'>
          <div className='round-portrait'>
            <Image
              src='/img/sampleHeadshot.jpg'
              height={200}
              width={200}
              className='round-portrait__img'
            />
          </div>
          <div className='blurb-body'>
            <h2>Katelyn Sansone</h2>
            <p>The road to your healing begins here</p>
            <p className='small-blurb'>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum
              accusantium voluptatum iure ex quaerat aut distinctio, nihil
              ducimus laborum alias dolores optio a, voluptatibus, nisi ipsam
              tempora eum suscipit est? Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Ullam animi culpa, amet aliquam nam inventore
              facere error atque nisi dolore quasi recusandae incidunt cumque,
              quaerat beatae quam! Corrupti, laboriosam obcaecati.
            </p>
            <p className='small-blurb'>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum
              accusantium voluptatum iure ex quaerat aut distinctio, nihil
              ducimus laborum alias dolores optio a, voluptatibus, nisi ipsam
              tempora eum suscipit est? Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Ullam animi culpa, amet aliquam nam inventore
              facere error atque nisi dolore quasi recusandae incidunt cumque,
              quaerat beatae quam! Corrupti, laboriosam obcaecati.
            </p>
            <div className='blurb-btn'>
              <Link href='/about'>
                <a>Learn more</a>
              </Link>
            </div>
          </div>
        </aside>
      </section>
      <section className='quote-parent'>
        <h4>
          "Our wounds are often the openings into the best and most beautiful
          parts of us."
        </h4>
        <p>- Kanye West</p>
      </section>
      <section className='info-block'>
        <aside className='info-block__sm-body'>
          <h3>Specialties</h3>
        </aside>
        <div className='info-block__widgets'>
          <SpecialtiesInfo />
          {/* <div className='info-block__icon'></div>
          <div className='info-block__icon'></div>
          <div className='info-block__icon'></div> */}
        </div>
      </section>
      <section className='contact-block'>
        <Contact />
      </section>
    </div>
  )
}
